### ISSUE TITLE
Include Eboard Size on Eboard Page

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/blueprint#15]
One of the things I needed most often as President when I looked at the org chart was just to know how many people were currently on the board. I used this to plan recruiting but also to do things like figure out how much food to order or how big an airbnb to get. 

On the current blueprint page, some people show up twice (because they have multiple positions), so it's hard to get a headcount. Showing the count on the page directly would really help.

**Comment by Havaldar** [comment]
Did this its in dev! you can close the issue
